### ISSUE TITLE
[Discussion] Increasing the scope of the project

### ISSUE THREAD

**Issue by raivivek** [metakgp/gyft#19]
This issue is not about a specific post. I'd rather like to discuss a few things that increase the scope of the project.
- [x] 'Export' calender (*.ics files, I believe) or create a per user link that people can add to their own calender. 
- [ ] Having worked on `naarad`, we can scrape events from most of the society pages periodically and create calender events - no need to do anything manually. This, too, can be offered as an exported calender.

I do not know what are the specific issues in implementing these, but I think that the above combined with a resolution of existing issues will really pack a punch.

Ideas?

cc/ @athityakumar @DefCon-007 @icyflame @hargup

**Comment by athityakumar** [comment]
@vivekiitkgp : Great idea! Maybe we can ask the user to input a list of societies they'd like to be notified from. We'll anyway scrape all posts & events from all (mostly) societies and store it in `feed.json`. So, we can get details (posts & events) of the particular set of societies that the user is interested in - from the `feed.json` file. 

Then, we can add events to the user's calendar. Along with adding events to calendar (exploit `gyft`) , we can also send the user mails periodically about the posts of the societies (exploit `FaceMail`).

But, we need to run all of them as a cron job with complete automation. Also, we might need a RoR / Django interface for the user to interact.

**Comment by icyflame** [comment]
@athityakumar @vivekiitkgp 

The ICS file idea is really cool. That gives the flexibility of adding to iPhones as well, and keeps things separate from your primary calendar. I haven't used this because I don't want my main calendar to be filled with events from the semester. I will look into libraries that generate ICS files in Python.

For the second one, we need to give them a link to a live updating calendar. This is done by things like Formula 1, where they give you a link which you can add to your google calendar and that will automatically be updated, whenever they update something at their end. I don't have any clue how to do this from an API. Interesting ideas!

**Comment by icyflame** [comment]
@vivekiitkgp Your ICS file idea is really good. That will provide a good way to import into google calendar from calendar.google.com, and we wouldn't have to worry about any kind of API keys, etc.

I have written the basic event generating function [here](https://github.com/icyflame/gyft/blob/b305fc0a17c7c7df6c2f930d6ae17577f91721d8/test.py). I will have to have a look through the existing code to figure out how to integrate it. Shouldn't be too hard. Will try to put together a patch soon.

**Comment by DefCon-007** [comment]
@athityakumar @vivekiitkgp  Inspite of adding events directly to a user's account we can first add them to like say metakgp's account and then let users subscribe to that calendar. In this way we wont be needing the user's access token. 
We can make different calendar for different societies so that people can choose what events they want to subscribe.

**Comment by icyflame** [comment]
@DefCon-007 Different societies would lead to a whole lot of calendars. We can maybe group societies into different genres.

**Comment by DefCon-007** [comment]
@icyflame That would be a problem. The user will receive notifications from the one he/she don't want to and it will be seriously annoying. For eg. if we put say Encore and Pravaah in the same category and I like to know only about the events of Encore then I will receive unnecessary notifications on Pravaah.

**Comment by vivekiitkgp** [comment]
Not necessarily. All the events will be in a separate calender. You will
*copy* the events to your own calender if you wish to be notified about
only a few of them.

--
https://vivekiitkgp.github.io

**Comment by DefCon-007** [comment]
@vivekiitkgp : That will be nice

**Comment by vivekiitkgp** [comment]
@nishnik This is the issue I was talking about when we last met in CCD (for discussing the meet with S K Barai). Do you have any comments?

@icyflame Thanks for the heads up. Seems like a great start.

**Comment by proffapt** [comment]
ApnaInsti will be having this very calendar, with following features to be noted:
- Society and event type based subscription
- Non-gymk based societies will also be included
- Events Calendar will be there

Closing the issue for the reasons above so that some others don't start working on this.
