### ISSUE TITLE
Add lab lists in subjects.json

### ISSUE THREAD

**Issue by nishnik** [metakgp/gyft#3]
Labs are not included in current `subjects.json`

**Comment by icyflame** [comment]
@nishnik I am writing code for this to be crowd sourced. So, whenever a user uses this. We check all their subjects, if one isn't there, then we will immediately get the new value from them.

I have written this much, but I am not sure how to proceed after this? Write a simple API to which a POST request can be made, so that we can add it to our `subjects.json` and thus, propagate the changes to everyone else.

Diff: https://github.com/metakgp/gyft/compare/master...icyflame:crowd-source-subjects?expand=1

Some things still pending:

- Get path from subjects.json if it is not there in any of the expected paths
- Figure out how to send the new subject name from the local machine of the user to our backend and eventually push it to GitHub

cc @athityakumar 

What do you think?

**Experience:**

![image](https://cloud.githubusercontent.com/assets/3668034/17668714/40ba0cd0-6328-11e6-8fc7-aab26fe784a4.png)

**Code:**

**Comment by nishnik** [comment]
The idea looks nice! :beer:

**Comment by vivekiitkgp** [comment]
How does our subject coverage looks now?

**Comment by icyflame** [comment]
I just discovered three of my subjects this semester are not there in the json. I will add them.

But note that we have many copies of subject.json now. One in mfqp-source, gyft, etc. Can you think of a way to have just one copy of the file, which can be referred everywhere else?

**Comment by vivekiitkgp** [comment]
One way is to literally create a subjects.json repository and have all other projects pull it as a submodule. I like it. Otherwise, if the projects reside on same machine, using some symlink magic can help.

Though honestly, the first one sounds way cool.

**Comment by icyflame** [comment]
@vivekiitkgp Submodule is DEFINITELY the way to go. GREAT idea. I am pretty sure submodules were designed for exactly this kind of application.
